# -*- coding: utf-8 -*-
"""LFW_Face_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5lym0gtU0JzTNvCcEpH4NSCPdACczhK

# Facial Detection with the Haar Cascade Classifier
"""

from google.colab import drive
drive.mount('/content/gdrive')

import warnings
warnings.filterwarnings('ignore') # Ignore warnings for cleaner output
import os
import random
from PIL import Image
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import numpy as np
import cv2

data_dir_path = "/content/gdrive/My Drive/Masters/"
all_files = os.listdir(data_dir_path)
all_files

import pandas as pd

# Read metadata about the dataset
allNames = pd.read_csv("/content/gdrive/My Drive/Masters/lfw_allnames.csv")
# Display summary statistics of the number of images per person
allNames["images"].describe()

# Define the path to the images directory
images_data_dir = os.path.join(data_dir_path, 'lfw-deepfunneled', 'lfw-deepfunneled')

# Get the list of persons (directories) in the images directory
persons = os.listdir(images_data_dir)
len(persons)

random_person = np.random.choice(persons, 15, replace = False) # replace = False means no duplicate.
select_images = []
for person in random_person:
    person_dir = os.path.join(images_data_dir, person)
    person_file = os.listdir(person_dir)
    select_person_image_file = random.choice(person_file)
    select_images.append(os.path.join(person_dir, select_person_image_file))

select_images

fig, axs = plt.subplots(3, 5, figsize = (15, 9))
for i, image_path in enumerate(select_images):
    img = mpimg.imread(image_path)
    axs[i // 5, i % 5].imshow(img)
    axs[i // 5, i % 5].set_title(select_images[i].split('/')[-2])
    axs[i // 5, i % 5].axis('off')

plt.show()

# Plotting images with bounding boxes
fig, axs = plt.subplots(3, 5, figsize=(15, 9))
for i, image_path in enumerate(select_images):
    img = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

     # Detect faces in the image
    face_detect = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
    faces = face_detect.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30))

    # Draw bounding boxes around detected faces
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

    axs[i // 5, i % 5].imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    axs[i // 5, i % 5].set_title(image_path.split('/')[-2]) # Extract person's name from the path
    axs[i // 5, i % 5].axis('off')
    axs[i // 5, i % 5].axis('off')

plt.show()