# -*- coding: utf-8 -*-
"""LFW_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYJb7QNCq2p_cTF6iuF12_RkTnZyJvYR

# Explanatory Data Analysis

The dataset used in this notebook is **Labelled faces in the wild**. We edited the people.csv dataset provided by Kaggle, to include gender and race. By going through each and every photo within the dataset to correctly identify the gender and race.
"""

from google.colab import drive
drive.mount('/content/gdrive')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import os

"""## Original Data"""

data = pd.read_csv('/content/gdrive/My Drive/Masters/people.csv')
data.head()

"""## Edited Data"""

df = pd.read_csv('/content/gdrive/My Drive/Masters/people_gender_race.csv')
df.head()

"""**Name** is the name of the labelled face. \\
**Images** is the number of images of that person. \\
**Gender** is Male (0) and Female (1). \\
**Race** is White/Caucasian (0), Black/Coloured (1), Middle Eastern (2), Asian (3) and Hispanic/Latino (4).
"""

sns.barplot(df['images'].value_counts()[:10], palette= "tab10")
plt.title('Top 10 Most Frequent Images')
plt.xlabel('Images')
plt.ylabel('Count')
plt.show()

"""## Gender"""

sns.barplot(y=list(df['gender'].value_counts().values),x= list(df['gender'].value_counts().index), palette= "tab10")
ax = plt.subplot()
ax = ax.set_xticklabels(["Male","Female"])

"""## Race"""

sns.barplot(y=list(df['race'].value_counts().values),x= list(df['race'].value_counts().index), palette= "tab10")
ax = plt.subplot()
ax = ax.set_xticklabels(["Caucasian", "Black/Colored", "MiddleEastern", "Asian", "Hispanic/Latino"])

# Libraries
import os
import glob
import random
import cv2
import base64
import imageio
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as data_utils
from copy import deepcopy
from torch.autograd import Variable
from tqdm import tqdm
from pprint import pprint
from PIL import Image
from sklearn.model_selection import train_test_split
import os

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print('Training on',DEVICE)

DATASET_PATH ="/content/gdrive/My Drive/Masters/lfw-deepfunneled/lfw-deepfunneled/"
ATTRIBUTES_PATH = "/content/gdrive/My Drive/Masters/lfw_attributes.csv"

dataset = []
for path in glob.iglob(os.path.join(DATASET_PATH, "**", "*.jpg")):
    person = path.split("/")[-2]
    dataset.append({"name":person, "path": path})

dataset = pd.DataFrame(dataset)
#too much Bush
dataset = dataset.groupby("name").filter(lambda x: len(x) < 25 )
dataset.head(10)

"""## Num. photos per person"""

random_sample = dataset.groupby("name").count().sample(n=100, random_state=1)

random_sample.plot(kind='bar', figsize=(15, 5))

plt.show()

"""## Example of the Labelled Faces in Wild"""

plt.figure(figsize=(20,10))
for i in range(20):
    idx = random.randint(0, len(dataset))
    img = plt.imread(dataset.path.iloc[idx])
    plt.subplot(4, 5, i+1)
    plt.imshow(img)
    plt.title(dataset.name.iloc[idx])
    plt.xticks([])
    plt.yticks([])
plt.tight_layout()
plt.show()